default:
  stackName: sat-api

  system_bucket: change-me 

  tags:
    project: sat-api

  capabilities:
    - CAPABILITY_IAM

  es:
    name: es6
    version: '6.0'
    instanceCount: 1
    instanceType: t2.small.elasticsearch
    volumeSize: 35 

  apis:
    - name: stac

  lambdas:
    ingest:
      source: 'node_modules/@sat-utils/ingest/dist/'
      handler: index.handler
      timeout: 900
      memory: 768
      envs:
        bucket: '{{system_bucket}}'
        prefix: '{{stackName}}'
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
        ECS_ROLE_ARN: "!GetAtt ECSRole.Arn"
        CLUSTER_ARN: "!GetAtt SatApiECSCluster.Arn"
        TASK_ARN: "!Ref SatApiTaskDefinition"
    api:
      source: 'node_modules/@sat-utils/api/dist/'
      handler: index.handler
      timeout: 100
      envs:
        ES_HOST: "!GetAtt {{es.name}}Domain.DomainEndpoint"
      apiGateway:
        - api: stac
          path: '{proxy+}'
          method: get
          cors: true

  tasks:
    SatApi:
      image: satutils/sat-api:latest
      cpu: 1024
      memory: 2048
      envs:
        stackName: '{{stackName}}'