version: 2

references:
  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  prod:
    docker:
      - image: circleci/node:8.11
    steps:
      - *restore_repo
      - checkout
      - run:
          name: Install
          command: |
            yarn
      - run:
          name: Deploy to aws
          command: |
            if [[  "$CIRCLE_BRANCH" == 'master' ]]; then
              echo 'master'
              # TODO
            fi

  dev:
    machine:
      docker_layer_caching: true
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
      - run:
          name: Build Docker image
          command: |
            touch .env
            docker-compose build
      - run:
          name: Deploy
          command: |
            if [[  "$CIRCLE_BRANCH" == 'develop' ]]; then
              echo 'dev'
              # TODO
            fi


workflows:
  version: 2
  prod:
    jobs:
      - prod:
          filters:
            branches:
              only: master
  dev:
    jobs:
      - dev:
          filters:
            branches:
              only: develop
